#!/bin/bash

set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

export DOCKER_BUILDKIT=1
PROJECTS=(
	'graph-altimeter-local'
	'graph-altimeter-dev-altimeter'
	'graph-altimeter-test'
	'graph-altimeter-lint'
)
for project in ${PROJECTS[@]}; do
	echo "Cleaning up ${project}" >&2
	docker-compose -p "${project}" rm -s -f
done
