#!/bin/bash

set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

export LINTER_PATHS=${@:-'graph_altimeter bin tests'}
echo "Linter paths: '${LINTER_PATHS}'"

export DOCKER_BUILDKIT=1
DOCKER_COMPOSE_PROJECT='graph-altimeter-lint'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-altimeter-lint
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run graph-altimeter-lint
