#!/bin/bash

# Exit on error and undefined variable.
set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

# Set paths to be scanned by the linters.
export LINTER_PATHS=${@:-'graph_altimeter bin tests'}
echo "Linter paths: '${LINTER_PATHS}'"

# Run the docker-compose lint environment.
DOCKER_COMPOSE_PROJECT='graph-altimeter-lint'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-altimeter-lint
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run graph-altimeter-lint
