#!/bin/bash

# Exit on error and undefined variable.
set -e -u

# Set working directory to the root of the repo.
cd "$(dirname "$0")/.."

ENV_FILE=""
NOTEBOOKS="./notebooks"
case $# in
1)
	ENV_FILE=$1
	;;
2)
	ENV_FILE=$1
	NOTEBOOKS=$2
	;;
*)
	echo "usage: $0 envfile [notebooks_path]" >&2
	exit 2
	;;
esac
export ENV_FILE
export NOTEBOOKS

echo "using notebooks dir: ${NOTEBOOKS}"

# Run the docker-compose local environment.
DOCKER_COMPOSE_PROJECT='graph-altimeter-local'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-altimeter-local
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run graph-altimeter-local
