#!/bin/bash

# Exit on error and undefined variable.
set -e -u

# Set working directory to the root of the repo.
cd "$(dirname "$0")/.."

ENV_FILE=""
NOTEBOOKS="./notebooks"
case $# in
1)
	ENV_FILE=$1
	;;
2)
	ENV_FILE=$1
	NOTEBOOKS=$2
	;;
*)
	echo "usage: $0 envfile [notebooks_path]" >&2
	exit 2
	;;
esac
export ENV_FILE
export NOTEBOOKS

echo "using notebooks dir: ${NOTEBOOKS}"

# External dependencies.
mkdir -p extern

# Altimeter.
ALTIMETER_REPO='https://github.com/manelmontilla/altimeter.git'
ALTIMETER_BRANCH='dev'
if [[ ! -d 'extern/altimeter' ]]; then
	git clone -b "${ALTIMETER_BRANCH}" "${ALTIMETER_REPO}" "extern/altimeter"
else
	echo 'skipping altimeter clone...' >&2
fi

# Run the docker-compose local altimeter environment.
DOCKER_COMPOSE_PROJECT='graph-altimeter-local-altimeter'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-altimeter-local-altimeter
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run graph-altimeter-local-altimeter
