#!/bin/bash

set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

export PYTEST_FLAGS="--ignore=extern $@"
echo "pytest flags: '${PYTEST_FLAGS}'"

export DOCKER_BUILDKIT=1
DOCKER_COMPOSE_PROJECT='graph-altimeter-test'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-altimeter-test
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run \
	-u "$(id -u):$(id -g)" \
	graph-altimeter-test
